spring.application.name=demoapp
#config conexion db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lp3_pcentral
spring.datasource.username=queavos
spring.datasource.password=superpass

# config JPA
spring.jpa.hibernate.ddl-auto=update 
# hacer el que ddl se genere y se ejecute
spring.jpa.show-sql=true 
#muestra las sentencias SQL q genera jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.sql=true



